# Generated by Django 5.1.4 on 2025-01-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0003_post_delete_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='image_of_the_cons',
            field=models.ImageField(blank=True, help_text='optionnal', null=True, upload_to='Image_of_the_cons/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_of_the_pros',
            field=models.ImageField(blank=True, help_text='optionnal', null=True, upload_to='Image_of_the_pros/'),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='post',
            name='name_of_the_country',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_of_the_cons',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='paragraph_of_the_pros',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='praragraph_that_represents_the_country',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
