# Generated by Django 4.2.3 on 2025-01-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0004_remove_post_body_remove_post_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='continent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api_model.continent'),
            preserve_default=False,
        ),
    ]
