# Generated by Django 5.1.4 on 2025-01-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0005_continent_post_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Image_Of_The_Country'),
        ),
    ]
