# Generated by Django 5.1.4 on 2025-01-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0007_post_image_2_post_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Image_Of_The_Country'),
        ),
    ]
