# Generated by Django 5.1.4 on 2025-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_model', '0008_post_image_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
